In [1]:
using DataFrames

# Split-apply-combine
## Grouping a data frame

In [3]:
x = DataFrame(id=[1,2,3,4,1,2,3,4], id2=[1,2,1,2,1,2,1,2], v=rand(8))

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.431328
   2 │     2      2  0.0905978
   3 │     3      1  0.317119
   4 │     4      2  0.956026
   5 │     1      1  0.503421
   6 │     2      2  0.564695
   7 │     3      1  0.1342
   8 │     4      2  0.968108

In [4]:
groupby(x, :id)


GroupedDataFrame with 4 groups based on key: id
First Group (2 rows): id = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421
⋮
Last Group (2 rows): id = 4
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.956026
   2 │     4      2  0.968108

In [5]:
groupby(x, [])

GroupedDataFrame with 1 group based on key: 
First Group (8 rows): 
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.431328
   2 │     2      2  0.0905978
   3 │     3      1  0.317119
   4 │     4      2  0.956026
   5 │     1      1  0.503421
   6 │     2      2  0.564695
   7 │     3      1  0.1342
   8 │     4      2  0.968108

In [6]:
gx2 = groupby(x, [:id, :id2])

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.956026
   2 │     4      2  0.968108

In [7]:
parent(gx2) # get the parent DataFrame

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.431328
   2 │     2      2  0.0905978
   3 │     3      1  0.317119
   4 │     4      2  0.956026
   5 │     1      1  0.503421
   6 │     2      2  0.564695
   7 │     3      1  0.1342
   8 │     4      2  0.968108

In [8]:
vcat(gx2...) # back to the DataFrame, but in a different order of rows than the original

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421
   3 │     2      2  0.0905978
   4 │     2      2  0.564695
   5 │     3      1  0.317119
   6 │     3      1  0.1342
   7 │     4      2  0.956026
   8 │     4      2  0.968108

In [9]:
DataFrame(gx2) # the same

8×3 DataFrame
 Row │ id     id2    v         
     │ Int64  Int64  Float64   
─────┼─────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421
   3 │     2      2  0.0905978
   4 │     2      2  0.564695
   5 │     3      1  0.317119
   6 │     3      1  0.1342
   7 │     4      2  0.956026
   8 │     4      2  0.968108

In [10]:
DataFrame(gx2, keepkeys=false) # drop grouping columns when creating a data frame


8×1 DataFrame
 Row │ v         
     │ Float64   
─────┼───────────
   1 │ 0.431328
   2 │ 0.503421
   3 │ 0.0905978
   4 │ 0.564695
   5 │ 0.317119
   6 │ 0.1342
   7 │ 0.956026
   8 │ 0.968108

In [11]:
groupcols(gx2) # vector of names of grouping variables

2-element Vector{Symbol}:
 :id
 :id2

In [12]:
valuecols(gx2) # and non-grouping variables


1-element Vector{Symbol}:
 :v

In [13]:
groupindices(gx2) # group indices in parent(gx2)

8-element Vector{Union{Missing, Int64}}:
 1
 2
 3
 4
 1
 2
 3
 4

In [14]:
kgx2 = keys(gx2)

4-element DataFrames.GroupKeys{GroupedDataFrame{DataFrame}}:
 GroupKey: (id = 1, id2 = 1)
 GroupKey: (id = 2, id2 = 2)
 GroupKey: (id = 3, id2 = 1)
 GroupKey: (id = 4, id2 = 2)

You can index into a `GroupedDataFrame` like to a vector or to a dictionary. The second form acceps `GroupKey`, `NamedTuple` or a `Tuple`


In [15]:
gx2

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.956026
   2 │     4      2  0.968108

In [16]:
k = keys(gx2)[1]

GroupKey: (id = 1, id2 = 1)

In [17]:
ntk = NamedTuple(k)

(id = 1, id2 = 1)

In [18]:
tk = Tuple(k)


(1, 1)

the operations below produce the same result and are fast

In [19]:
gx2[1]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421

In [20]:
gx2[k]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421

In [21]:
gx2[ntk]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421

In [22]:
gx2[tk]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.431328
   2 │     1      1  0.503421

In [23]:
x = DataFrame(id = [missing, 5, 1, 3, missing], x = 1:5)

5×2 DataFrame
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │       5      2
   3 │       1      3
   4 │       3      4
   5 │ missing      5

In [24]:
groupby(x, :id) # by default groups include mising values and their order is not guaranteed

GroupedDataFrame with 4 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (2 rows): id = missing
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │ missing      5

In [25]:
groupby(x, :id, sort=true, skipmissing=true) # but we can change it; now they are sorted

GroupedDataFrame with 3 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (1 row): id = 5
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      5      2

In [26]:
groupby(x, :id, sort=false) # and now they are in the order they appear in the source data frame

GroupedDataFrame with 4 groups based on key: id
First Group (2 rows): id = missing
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │ missing      5
⋮
Last Group (1 row): id = 3
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      3      4

## Performing transformations by group using `combine`, `select`, `select!`, `transform`, and `transform!`


In [28]:
using Statistics
using Chain
ENV["LINES"] = 15 # reduce the number of rows in the output
x = DataFrame(id=rand('a':'d', 100), v=rand(100))


100×2 DataFrame
 Row │ id    v          
     │ Char  Float64    
─────┼──────────────────
   1 │ c     0.432541
   2 │ b     0.779688
   3 │ c     0.557867
  ⋮  │  ⋮        ⋮
  98 │ b     0.832816
  99 │ a     0.0522582
 100 │ d     0.686185
         94 rows omitted

In [29]:
# apply a function to each group of a data frame
# combine keeps as many rows as are returned from the function
@chain x begin
    groupby(:id)
    combine(:v => mean)
end

4×2 DataFrame
 Row │ id    v_mean   
     │ Char  Float64  
─────┼────────────────
   1 │ c     0.45929
   2 │ b     0.513637
   3 │ a     0.403842
   4 │ d     0.507345

In [30]:
x.id2 = axes(x, 1)

Base.OneTo(100)

In [31]:
# select and transform keep as many rows as are in the source data frame and in correct order
# additionally transform keeps all columns from the source
@chain x begin
    groupby(:id)
    transform(:v => mean)
end

100×4 DataFrame
 Row │ id    v           id2    v_mean   
     │ Char  Float64     Int64  Float64  
─────┼───────────────────────────────────
   1 │ c     0.432541        1  0.45929
   2 │ b     0.779688        2  0.513637
   3 │ c     0.557867        3  0.45929
  ⋮  │  ⋮        ⋮         ⋮       ⋮
  98 │ b     0.832816       98  0.513637
  99 │ a     0.0522582      99  0.403842
 100 │ d     0.686185      100  0.507345
                          94 rows omitted

In [32]:
# note that combine reorders rows by group of GroupedDataFrame
@chain x begin
    groupby(:id)
    combine(:id2, :v => mean)
end

100×3 DataFrame
 Row │ id    id2    v_mean   
     │ Char  Int64  Float64  
─────┼───────────────────────
   1 │ c         1  0.45929
   2 │ c         3  0.45929
   3 │ c         9  0.45929
  ⋮  │  ⋮      ⋮       ⋮
  98 │ d        83  0.507345
  99 │ d        85  0.507345
 100 │ d       100  0.507345
              94 rows omitted

In [33]:
# we give a custom name for the result column
@chain x begin
    groupby(:id)
    combine(:v => mean => :res)
end

4×2 DataFrame
 Row │ id    res      
     │ Char  Float64  
─────┼────────────────
   1 │ c     0.45929
   2 │ b     0.513637
   3 │ a     0.403842
   4 │ d     0.507345

In [34]:
# you can have multiple operations
@chain x begin 
    groupby(:id)
    combine(:v => mean => :res1, :v => sum => :res2, nrow => :n)
end

4×4 DataFrame
 Row │ id    res1      res2      n     
     │ Char  Float64   Float64   Int64 
─────┼─────────────────────────────────
   1 │ c     0.45929   11.4823      25
   2 │ b     0.513637  13.8682      27
   3 │ a     0.403842   8.07685     20
   4 │ d     0.507345  14.2057      28

Additional notes:

* `select!` and `transform!` perform operations in-place
* The general syntax for transformation is source_columns => function => target_column
* if you pass multiple columns to a function they are treated as positional arguments
* you can automatically groupby again the result of combine, select etc. by passing `ungroup=false` keyword argument to them
* similarly `keepkeys` keyword argument allows you to drop grouping columns from the resulting data frame

It is also allowed to pass a function to all these functions (also - as a special case, as a first argument). In this case the return value can be a table. In particular it allows for an easy dropping of groups if you return an empty table from the function.

If you pass a function you can use a do block syntax. In case of passing a function it gets a SubDataFrame as its argument.

Here is an example:

In [35]:
combine(groupby(x, :id)) do sdf
    n = nrow(sdf)
    n < 25 ? DataFrame() : DataFrame(n=n) # drop groups with low number of rows
end

3×2 DataFrame
 Row │ id    n     
     │ Char  Int64 
─────┼─────────────
   1 │ c        25
   2 │ b        27
   3 │ d        28

You can also produce multiple columns in a single operation, e.g.:

In [36]:
df = DataFrame(id=[1,1,2,2], val=[1,2,3,4])

4×2 DataFrame
 Row │ id     val   
     │ Int64  Int64 
─────┼──────────────
   1 │     1      1
   2 │     1      2
   3 │     2      3
   4 │     2      4

In [37]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => AsTable)
end

2×3 DataFrame
 Row │ id     x1     x2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

In [38]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => [:c1, :c2])
end

2×3 DataFrame
 Row │ id     c1     c2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

It is easy to unnest the column into multiple columns, e.g.

In [39]:
df = DataFrame(a=[(p=1, q=2), (p=3, q=4)])

2×1 DataFrame
 Row │ a              
     │ NamedTup…      
─────┼────────────────
   1 │ (p = 1, q = 2)
   2 │ (p = 3, q = 4)

In [40]:
select(df, :a => AsTable)

2×2 DataFrame
 Row │ p      q     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

In [41]:
df = DataFrame(a=[[1, 2], [3, 4]])

2×1 DataFrame
 Row │ a      
     │ Array… 
─────┼────────
   1 │ [1, 2]
   2 │ [3, 4]

In [42]:
select(df, :a => AsTable) # automatic column names generated


2×2 DataFrame
 Row │ x1     x2    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

In [43]:
select(df, :a => [:C1, :C2]) # custom column names generated

2×2 DataFrame
 Row │ C1     C2    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

Finally, observe that one can conveniently apply multiple transformations using broadcasting:

In [44]:
df = DataFrame(id=repeat(1:10, 10), x1=1:100, x2=101:200)

100×3 DataFrame
 Row │ id     x1     x2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1    101
   2 │     2      2    102
   3 │     3      3    103
  ⋮  │   ⋮      ⋮      ⋮
  98 │     8     98    198
  99 │     9     99    199
 100 │    10    100    200
            94 rows omitted

In [45]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> minimum)
end


10×3 DataFrame
 Row │ id     x1_minimum  x2_minimum 
     │ Int64  Int64       Int64      
─────┼───────────────────────────────
   1 │     1           1         101
   2 │     2           2         102
   3 │     3           3         103
  ⋮  │   ⋮        ⋮           ⋮
   8 │     8           8         108
   9 │     9           9         109
  10 │    10          10         110
                       4 rows omitted

In [46]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> [minimum maximum])
end

10×5 DataFrame
 Row │ id     x1_minimum  x2_minimum  x1_maximum  x2_maximum 
     │ Int64  Int64       Int64       Int64       Int64      
─────┼───────────────────────────────────────────────────────
   1 │     1           1         101          91         191
   2 │     2           2         102          92         192
   3 │     3           3         103          93         193
  ⋮  │   ⋮        ⋮           ⋮           ⋮           ⋮
   8 │     8           8         108          98         198
   9 │     9           9         109          99         199
  10 │    10          10         110         100         200
                                               4 rows omitted

## Aggregation of a data frame using mapcols

In [47]:
x = DataFrame(rand(10, 10), :auto)

10×10 DataFrame
 Row │ x1         x2        x3          x4        x5         x6         x7     ⋯
     │ Float64    Float64   Float64     Float64   Float64    Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.017368   0.168686  0.933893    0.909083  0.984198   0.580141   0.9101 ⋯
   2 │ 0.445297   0.767357  0.273591    0.682757  0.258265   0.177115   0.5858
   3 │ 0.81921    0.630443  0.932345    0.244414  0.0227127  0.23128    0.4259
  ⋮  │     ⋮         ⋮          ⋮          ⋮          ⋮          ⋮          ⋮  ⋱
   8 │ 0.996049   0.353986  0.506745    0.398238  0.995444   0.652805   0.6528
   9 │ 0.073429   0.610063  0.924426    0.298547  0.228351   0.527504   0.9119 ⋯
  10 │ 0.803948   0.353707  0.938368    0.354815  0.919325   0.0288723  0.6103
                                                    4 columns and 4 rows omitted

In [48]:
mapcols(mean, x)

1×10 DataFrame
 Row │ x1        x2        x3        x4        x5        x6        x7        x ⋯
     │ Float64   Float64   Float64   Float64   Float64   Float64   Float64   F ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.430732  0.507986  0.549125  0.524228  0.529286  0.359171  0.559693  0 ⋯
                                                               3 columns omitted

## Mapping rows and columns using `eachcol` and `eachrow`


In [49]:
map(mean, eachcol(x)) # map a function over each column and return a vector

10-element Vector{Float64}:
 0.4307316290295839
 0.5079863449806338
 0.5491247189130867
 0.52422804522142
 0.5292857576605206
 0.35917103817028684
 0.5596928431682949
 0.4645368237724785
 0.6539731738126912
 0.5173236352225387

In [50]:
# an iteration returns a Pair with column name and values
foreach(c -> println(c[1], ": ", mean(c[2])), pairs(eachcol(x)))

x1: 0.4307316290295839
x2: 0.5079863449806338
x3: 0.5491247189130867
x4: 0.52422804522142
x5: 0.5292857576605206
x6: 0.35917103817028684
x7: 0.5596928431682949
x8: 0.4645368237724785
x9: 0.6539731738126912
x10: 0.5173236352225387


In [51]:
# now the returned value is DataFrameRow which works as a NamedTuple but is a view to a parent DataFrame
map(r -> r.x1/r.x2, eachrow(x))

10-element Vector{Float64}:
 0.10296070569790451
 0.5802995585681167
 1.2994193056855783
 0.6389402596649496
 0.7396671239595247
 0.10308712340871672
 1.152112973017291
 2.813804848014652
 0.12036296221096472
 2.272922480876994

In [52]:
# it prints like a data frame, only the caption is different so that you know the type of the object
er = eachrow(x)

10×10 DataFrameRows
 Row │ x1         x2        x3          x4        x5         x6         x7     ⋯
     │ Float64    Float64   Float64     Float64   Float64    Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.017368   0.168686  0.933893    0.909083  0.984198   0.580141   0.9101 ⋯
   2 │ 0.445297   0.767357  0.273591    0.682757  0.258265   0.177115   0.5858
   3 │ 0.81921    0.630443  0.932345    0.244414  0.0227127  0.23128    0.4259
  ⋮  │     ⋮         ⋮          ⋮          ⋮          ⋮          ⋮          ⋮  ⋱
   8 │ 0.996049   0.353986  0.506745    0.398238  0.995444   0.652805   0.6528
   9 │ 0.073429   0.610063  0.924426    0.298547  0.228351   0.527504   0.9119 ⋯
  10 │ 0.803948   0.353707  0.938368    0.354815  0.919325   0.0288723  0.6103
                                                    4 columns and 4 rows omitted

In [53]:
er.x1 # you can access columns of a parent data frame directly


10-element Vector{Float64}:
 0.017368041622140895
 0.4452971570504485
 0.8192103195643368
 0.4851893916600032
 0.43048873693673295
 0.07349143114684198
 0.16284607961881536
 0.9960485483588055
 0.07342897147079275
 0.8039476128669221

In [54]:
# it prints like a data frame, only the caption is different so that you know the type of the object
ec = eachcol(x)

10×10 DataFrameColumns
 Row │ x1         x2        x3          x4        x5         x6         x7     ⋯
     │ Float64    Float64   Float64     Float64   Float64    Float64    Float6 ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.017368   0.168686  0.933893    0.909083  0.984198   0.580141   0.9101 ⋯
   2 │ 0.445297   0.767357  0.273591    0.682757  0.258265   0.177115   0.5858
   3 │ 0.81921    0.630443  0.932345    0.244414  0.0227127  0.23128    0.4259
  ⋮  │     ⋮         ⋮          ⋮          ⋮          ⋮          ⋮          ⋮  ⋱
   8 │ 0.996049   0.353986  0.506745    0.398238  0.995444   0.652805   0.6528
   9 │ 0.073429   0.610063  0.924426    0.298547  0.228351   0.527504   0.9119 ⋯
  10 │ 0.803948   0.353707  0.938368    0.354815  0.919325   0.0288723  0.6103
                                                    4 columns and 4 rows omitted

In [55]:
ec.x1 # you can access columns of a parent data frame directly


10-element Vector{Float64}:
 0.017368041622140895
 0.4452971570504485
 0.8192103195643368
 0.4851893916600032
 0.43048873693673295
 0.07349143114684198
 0.16284607961881536
 0.9960485483588055
 0.07342897147079275
 0.8039476128669221

## Transposing
you can transpose a data frame using permutedims:

In [56]:
df = DataFrame(reshape(1:12, 3, 4), :auto)

3×4 DataFrame
 Row │ x1     x2     x3     x4    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      4      7     10
   2 │     2      5      8     11
   3 │     3      6      9     12

In [57]:
df.names = ["a", "b", "c"]

3-element Vector{String}:
 "a"
 "b"
 "c"

In [58]:
permutedims(df, :names)

4×4 DataFrame
 Row │ names   a      b      c     
     │ String  Int64  Int64  Int64 
─────┼─────────────────────────────
   1 │ x1          1      2      3
   2 │ x2          4      5      6
   3 │ x3          7      8      9
   4 │ x4         10     11     12